        
name: Build and deploy ASP.Net Core app to Azure Web App - nutrapreps-admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
            STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .next/
            public/
            iisnode.yml
            package.json
            package-lock.json
            next.config.js
            src/middleware.ts
            server.js
            web.config
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A16CEAAFCD4465B9CED2CCDFD5F3EF7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_257B6EA602A34864968B892CB67DCEB1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7717D7C53EE14333B8A07F792998F725 }}        
      
      - name: Deploy to Azure Web App (Staging)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nutrapreps-admin'
          slot-name: 'Staging'
          package: .
          