name: Build and deploy ASP.Net Core app to Azure Web App - nutrapreps-admin

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: npm install, build, and test       
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .next/
            public/
            node_modules/
            iisnode.yml
            package.json
            package-lock.json
            next.config.js
            src/middleware.ts
            server.js
            web.config
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9501C1F62BF64C7D87EB398083A7F5BA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E8FF57E5A6B4BBA845FC8D5DFA8A43B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B999F58A9214CB2921BFF44583E2D77 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nutrapreps-admin'
          slot-name: 'staging'
          package: .